# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  
  zookeeper_kafka:
    #image: confluentinc/cp-zookeeper:4.1.1
    image: confluentinc/cp-zookeeper:5.4.0
    ports:
      - 2182:2182
    hostname: zookeeper_kafka
    container_name: zookeeper_kakfa
    ports:
      - 2182:2182
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      - app

  kafka:
    #image: confluentinc/cp-kafka:4.1.1
    image: confluentinc/cp-kafka:5.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper_kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper_kafka:2182'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
    networks: 
      - app

  kafka-manager:
    #image: zenko/kafka-manager:latest
    image: sheepkiller/kafka-manager:latest
    container_name: kafka-manager    
    ports:
      - "9000:9000"
    links:
      - zookeeper_kafka
      - kafka
    environment:
      ZK_HOSTS: zookeeper_kafka:2182
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks:
      - app

networks: 
  app:
    driver: bridge