# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.1
    ports:
      - 2181:2181
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      - app

  kafka:
    image: confluentinc/cp-kafka:4.1.1
    hostname: localhost
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
    networks: 
      - app

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: kafka-manager    
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks:
      - app

networks: 
  app:
    driver: bridge