version: '3'

services:
  kibana:    
    environment:
      ELASTICSEARCH_URL: http://elasticsearch.com:9200   
    image: docker.elastic.co/kibana/kibana-oss:6.2.1
    networks:
      - app
    ports:
    - 5601:5601
    restart: unless-stopped

networks: 
  app:
    driver: bridge

