version: '3.1'
services:
  db:
    image: mysql:5.7.36
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
