# docker compose to run Apache Pulsar and Pulsar dashboard

version: '3'

services:

  standalone:
    image: apachepulsar/pulsar
    container_name: pulsar-standalone
    ports:
      - 8080:8080
      - 6650:6650 
    environment:
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
    networks:
    - app

  dashboard:
    image: javac7/apachepulsar-dashboard
    container_name: pulsar-dashboard
    depends_on:
      - standalone
    ports:
      - 80:80
    environment:
      - SERVICE_URL=http://standalone:8080
    networks:
    - app

networks: 
  app:
    driver: bridge