version: '3.8'

services:
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb
    ports:
      - "28015:28015"   # driver port
      - "29015:29015"   # cluster port
      - "8080:8080"     # web interface
    volumes:
      - rethinkdb_data:/data
    restart: unless-stopped   
    networks:
      - rethinkdb-network

networks: 
  rethinkdb-network:
    driver: bridge

volumes:
  rethinkdb_data:
